CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    password TEXT NOT NULL,
    mfa TEXT NOT NULL,
    gendate TIMESTAMP NOT NULL,
    expired BOOLEAN NOT NULL DEFAULT FALSE
);
