version: 1.0
provider:
  name: openfaas
  gateway: http://98.66.243.201:8080
functions:
  register:
    lang: python3-flask
    handler: ./register/
    image: antonin187/mspr-bloc-2-register:latest
    environment:
      DATABASE_URL: postgresql://cofrap:postgres_pass@postgres.openfaas.svc.cluster.local:5432/mspr02
      ENCRYPTION_KEY: cxSCKh8NDwgloBrDyjQdg3on9wHZyQsAjmayA64X7Tg=
  login:
    lang: python3-flask
    handler: ./login/
    image: antonin187/mspr-bloc-2-login:latest
    environment:
      DATABASE_URL: postgresql://cofrap:postgres_pass@postgres.openfaas.svc.cluster.local:5432/mspr02
      ENCRYPTION_KEY: cxSCKh8NDwgloBrDyjQdg3on9wHZyQsAjmayA64X7Tg=
      SECRET_KEY: AziGo360NoScopeHeadShotTraversSmokeWhileBlindAuScoutCaPasseFirstTrySurVertigoEnRunBoost!
  regenerate:
    lang: python3-flask
    handler: ./regenerate/
    image: maximebdn/mspr-bloc-2-regenerate:latest
    environment:
      DATABASE_URL: postgresql://postgres:postgres_pass@postgres.default.svc.cluster.local:5432/mydb
      ENCRYPTION_KEY: cxSCKh8NDwgloBrDyjQdg3on9wHZyQsAjmayA64X7Tg=
      SECRET_KEY: AziGo360NoScopeHeadShotTraversSmokeWhileBlindAuScoutCaPasseFirstTrySurVertigoEnRunBoost!
  profile:
    lang: python3-flask
    handler: ./profile/
    image: maximebdn/mspr-bloc-2-profile:latest
    environment:
      DATABASE_URL: postgresql://postgres:postgres_pass@postgres.default.svc.cluster.local:5432/mydb
      ENCRYPTION_KEY: cxSCKh8NDwgloBrDyjQdg3on9wHZyQsAjmayA64X7Tg=
      SECRET_KEY: AziGo360NoScopeHeadShotTraversSmokeWhileBlindAuScoutCaPasseFirstTrySurVertigoEnRunBoost!