version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  register:
    lang: python3-flask
    handler: ./register/
    image: maximebdn/mspr-bloc-2-register:latest
    environment:
      DATABASE_URL: postgresql://postgres:postgres_pass@postgres.default.svc.cluster.local:5432/mydb
      ENCRYPTION_KEY: cxSCKh8NDwgloBrDyjQdg3on9wHZyQsAjmayA64X7Tg=
  login:
    lang: python3-flask
    handler: ./login/
    image: maximebdn/mspr-bloc-2-login:latest
    environment:
      DATABASE_URL: postgresql://postgres:postgres_pass@postgres.default.svc.cluster.local:5432/mydb
      ENCRYPTION_KEY: cxSCKh8NDwgloBrDyjQdg3on9wHZyQsAjmayA64X7Tg=
      SECRET_KEY: AziGo360NoScopeHeadShotTraversSmokeWhileBlindAuScoutCaPasseFirstTrySurVertigoEnRunBoost!